FROM openjdk:17
LABEL maintainer ="mani320"
ADD InventorySystem/target/InventorySystem-0.0.1-SNAPSHOT.jar InventorySystem-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","InventorySystem-0.0.1-SNAPSHOT.jar"]