version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  broker:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  order-service:
    image: prettyface/orderservice:latest
    ports:
      - "5003:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  inventory-service:
    image: gorm2303/inventoryservice:latest
    ports:
      - "5002:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  orderstore:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - ./mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
